[package]
edition = "2024"
name = "promatch-macros"
version = "0.1.0"

[lib]
proc-macro = true

[dependencies]
derive-syn-parse = "0.2"
heck = "0.5.0"
proc-macro2 = "1.0.95"
quote = "1.0.40"
syn = {version = "2.0.100", features = ["full"]}
